### PR TITLE
add breakfast

### PR DESCRIPTION
**Pull request by panitnt**

### CODE REVIEW

**Comment by Savetang19** [comment]
Are your items arranged alphabetically? Please rearrange it.

**Comment by premepreme** [comment]
pls rearrange alphabet

**Comment by khemissara** [comment]
pls rearrange the alphabet

**Comment by mjrchy** [comment]
Ok +1

**Review by Savetang19 — APPROVED** [review]
good +1

**Comment by khemissara** [comment]
very good +1

**Review by premepreme — APPROVED** [review]
good +1

**Pull request merged**
