### PR TITLE
add menu to beverage

### PR DESCRIPTION
**Pull request by premepreme**

### CODE REVIEW

**Comment by panitnt** [comment]
Are your items arranged alphabetically? Please rearrange it.

**Comment by khemissara** [comment]
pls the rearrange alphabet

**Review by Savetang19 — APPROVED** [review]
good +1

**Review by panitnt — APPROVED** [review]
+1

**Review by khemissara — APPROVED** [review]
+1

**Review by mjrchy — APPROVED** [review]
+1

**Comment by panitnt** [comment]
already edit spelling +1

**Review by Savetang19 — APPROVED** [review]
It it seems that there are no errors.

**Comment by khemissara** [comment]
no problem!

**Pull request merged**
